### ISSUE TITLE
Missing render settings

### ISSUE THREAD

**Issue by abyvinod** [abezukor/EquationEditorPP#1]
Thank you for creating this add-on. I was able to get multiple equations working with this add-on before running into an issue.

**Issue**: Render settings is blank. 

![image](https://user-images.githubusercontent.com/831079/85136553-635f6c00-b205-11ea-9546-81e2045891da.png)

**What have I (unsuccessfully) tried**:
1. Refreshing the google slides webpage
1. Try it in Google Chrome and Firefox

**Comment by abezukor** [comment]
The entire rendering pipeline was re-done in an update last month, so I am closing this issue. Feel free to leave another comment if it pops back up.
