### ISSUE TITLE
Inserting is not working

### ISSUE THREAD

**Issue by chrisflesher** [abezukor/EquationEditorPP#2]
I have used this tool before and it worked very well. Recently it seems when I enter an equation and hit the "Insert Equation into Document" button nothing happens. I am able to manually copy and paste the image but lose all of my equation info doing this. Any ideas on how to debug or fix this?

**Comment by i8sumPi** [comment]
I have the same problem, except I haven't used this tool before.

**Comment by zhangysh1995** [comment]
+1, fresh installation, still not inserting

**Comment by ysinotelodigo** [comment]
I have checked it and it works. You cannot use multi google account. 
I opened MS Edge with only one gmail account and it works.

**Comment by abezukor** [comment]
The entire rendering pipeline was re-done in an update last month, so I am closing this issue. Feel free to leave another comment if it pops back up.
