### ISSUE TITLE
Revert to previous version

### ISSUE THREAD

**Issue by baccione** [abezukor/EquationEditorPP#4]
It was working great until a few days ago.
Now it has a number of issues that makes the product a way worse.

- Rendering is horrible (low resolution)
- It does not import inserted equations anymore.

Just go back to the previous version.

**Comment by abezukor** [comment]
To address your points, the rendering resolution is not horrible. When you request 12px font, it renders an image with exactly that height, If you need higher resolution, render at a bigger font size, and shrink down the resultant images.

I cannot replicate not being able to import equations any more. Can you provide me more details? What is the alt-text of the equation you are trying to insert?

**Comment by abezukor** [comment]
Closing due to no response
